name: flutter_course
description: A new Flutter project.


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  scoped_model: "^0.3.0"
  http: "^0.11.3+16"
  shared_preferences: "^0.4.2"
  rxdart: "^0.17.0"
  map_view: "^0.0.14"
  location: "^1.4.1"
  image_picker: "^0.4.5"
  mime: "^0.9.6"
  url_launcher: "^3.0.2"
  cached_network_image: "^0.5.1"
  carousel_pro: ^0.0.13
  intl: ^0.15.7
  flutter_webview_plugin: ^0.2.1+2
  flutter_advanced_networkimage: any
  sqflite: ^0.12.0
  connectivity: ^0.3.2
  charts_flutter: ^0.4.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.6.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/isubu_logo.png"
  adaptive_icon_background: "#FFFAFAFA"
  adaptive_icon_foreground: "assets/icon/isubu_logo.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/food.jpg
    - assets/background.jpg
    - assets/sdu.jpg
    - assets/profil.jpg
    - assets/staff-default.png
    - assets/sdu_obs_giris.jpg
    - assets/anasayfa0.jpg
    - assets/menu_genel_tanitim.png
    - assets/anasayfa2.jpg
    - assets/anasayfa3.jpg
    - assets/load_json/akademik_takvim.json
    - assets/logo_108.png
    - assets/isubu_logo_opacity2.png
    - assets/isubu_logo_opacity.png
    - assets/ISUBU.jpg
    - assets/ISUBU_1.jpg
    - assets/ISUBU_2.jpg
    - assets/isubu_logo1.jpg



  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/Oswald-Bold.ttf
          weight: 700
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
